#pragma once

enum STATEMENT_TYPE{
    STATEMENT_TYPE_UNKNOWN = 0,
    STATEMENT_TYPE_EXPRESSION,
    STATEMENT_TYPE_BLOCK,
    STATEMENT_TYPE_BINARY,
    STATEMENT_TYPE_FUN,
    STATEMENT_TYPE_IF,
    STATEMENT_TYPE_STRING,
    STATEMENT_TYPE_NUMBER,
    STATEMENT_TYPE_DECLARATION,
};

enum BINARY_STATEMENT_OPERATOR{
    BINARY_STATEMENT_OPERATOR_UNKNOWN = 0,
    BINARY_STATEMENT_OPERATOR_ADD,
    BINARY_STATEMENT_OPERATOR_SUB,
    BINARY_STATEMENT_OPERATOR_MUL,
    BINARY_STATEMENT_OPERATOR_DIV,
};