#pragma once

enum STATEMENT_TYPE
{
    STATEMENT_TYPE_UNKNOWN = 0,
    STATEMENT_TYPE_ROOT = 1 << 1,
    STATEMENT_TYPE_EXPRESSION = 1 << 2,
    STATEMENT_TYPE_BLOCK = 1 << 3,
    STATEMENT_TYPE_BINARY = 1 << 4,
    STATEMENT_TYPE_FUN = 1 << 5,
    STATEMENT_TYPE_IF = 1 << 6,
    STATEMENT_TYPE_STRING = 1 << 7,
    STATEMENT_TYPE_NUMBER = 1 << 8,
    STATEMENT_TYPE_DECLARATION = 1 << 0,
};

enum BINARY_STATEMENT_OPERATOR
{
    BINARY_STATEMENT_OPERATOR_UNKNOWN = 0,
    BINARY_STATEMENT_OPERATOR_ADD,
    BINARY_STATEMENT_OPERATOR_SUB,
    BINARY_STATEMENT_OPERATOR_MUL,
    BINARY_STATEMENT_OPERATOR_DIV,
};

const size_t STATEMENT_TRANSLATION_MAP[1024] = {
    0,
    STATEMENT_TYPE_FUN | STATEMENT_TYPE_DECLARATION, // ROOT
};